openapi: '3.0.0'
info:
  version: 1.0.0
  title: Monerochan Merchant RPC
  description: An API to easily accept payments in Monero
servers:
  - url: /v1
paths:
  /wallet/initialize:
    post:
      description: |
        call this endpoint to create the wallet file from primary address and viewkey. \
        This is the first endpoint you need to call. Afterwards you can call the /wallet/sync endpoint. 
      summary: create the wallet file from primary address and viewkey
      operationId: initialize
      x-eov-operation-handler: routes/wallet/initialize 
      tags:
       - startup tasks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WalletInitialize'
            examples:
              Testnet:
                value:
                  path: ./monerochans_testnet_stash
                  networkType: testnet
                  primaryAddress: 9uJ5JRXP3BQAGW1nHK9KzVHUifBfCAHnJKRnZ45ebYcQJrt2wprNgYoGWJvPrCW6nSiBAzmeSAGBGjM5kt2mRb3g98JJetV
                  privateViewKey: d99cca1f6794a0a856cde057421702482b8d56e36f31a939239f97e9f5a32b0d
                  restoreHeight: 0
              Stagenet:
                value:
                  path: ./monerochans_stagenet_stash
                  networkType: stagenet
                  primaryAddress: 55Py9fSwyEeQX1CydtFfPk96uHEFxSxvD9AYBy7dwnYt9cXqKDjix9rS9AWZ5GnH4B1Z7yHr3B2UH2updNw5ZNJEEnv87H1
                  privateViewKey: 1195868d30373aa9d92c1a21514de97670bcd360c209a409ea3234174892770e
                  restoreHeight: 957038
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '500':
          description: unexpected error
  /wallet/sync:
    post:
      description: |
        call this endpoint to start syncing the wallet after the wallet file was created. \
        This is the second endpoint you need to call after creating the wallet file with /wallet/initialize. \
        Afterwards you can call the accept payments & check api health endpoints. Or shut things down orderly with the shutdown tasks.
      summary: start syncing the wallet after the wallet file was created.
      operationId: sync
      x-eov-operation-handler: routes/wallet/sync 
      tags:
       - startup tasks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WalletSync'
            examples:
              Testnet:
                value:
                  path: ./monerochans_testnet_stash
                  networkType: testnet
                  serverUri: http://localhost:28081

              Stagenet:
                value:
                  path: ./monerochans_stagenet_stash
                  networkType: stagenet
                  serverUri: http://stagenet.xmr-tw.org:38081

      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '500':
          description: unexpected error
  /make/invoice:
    post:
      description: |
        supply the path of the wallet where you want to receive the money. \
        as the payment_id you can use the autoincremented_id of a payment_request SQL table for example. \
        make sure this payment_id is unique per product and client so that you know which payment is for which product or service and which client it came from. \
        you can also use this endpoint to query just the exchange rate or just get an address. \
        It is all combined in this endpoint because these RPC calls are expensive and you will most likely need all of these things at once. The default currency is USD. Check out other supported currencies here: <a href="https://api.coingecko.com/api/v3/simple/supported_vs_currencies">https://api.coingecko.com/api/v3/simple/supported_vs_currencies</a>
        
      summary: get a unique address per client and product & the xmr exchange rate 
      operationId: invoice
      x-eov-operation-handler: routes/wallets/invoice
      tags:
       - accept payments & check api health
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MakeInvoice'
            examples:
              Testnet:
                value:
                  path: ./monerochans_testnet_stash
                  payment_id: 03284e41c342f036
                  amount: 10

              Stagenet:
                value:
                  path: ./monerochans_stagenet_stash
                  payment_id: 03284e41c342f036
                  amount: 10
              Testnet Amount in BTC:
                value:
                  path: ./monerochans_testnet_stash
                  payment_id: 03284e41c342f036
                  amount: 10
                  currency: btc
              Testnet Amount in EURO:
                value:
                  path: ./monerochans_testnet_stash
                  payment_id: 03284e41c342f036
                  amount: 10
                  currency: eur
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MakeInvoiceResponse'
        '500':
          description: unexpected error
  /wallets/status:
    get:
      description: |
        call this endpoint to get the syncing status of the currently opened wallets. \
        this endpoint can also be used check general api health (if the monerochan merchant api is still running).
      summary: check sync status on individual wallets and general api health
      operationId: status
      x-eov-operation-handler: routes/wallets/status
      tags:
       - accept payments & check api health
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WalletStatusResponse'
        '500':
          description: unexpected error
  /wallets/shutdown:
    post:
      description: |
        stop syncing and close wallets. \
        just send the paths of the wallets you want to close as an array. 
      summary: stop syncing and close individual wallets
      operationId: shutdown
      x-eov-operation-handler: routes/wallets/shutdown
      tags:
       - shutdown tasks
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WalletShutdown'
            examples:
              Shutdown Testnet and Stagenet :
                value:
                  - ./monerochans_testnet_stash
                  - ./monerochans_stagenet_stash
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '500':
          description: unexpected error
components:
  schemas:
    WalletInitialize:
      type: object
      properties:
        path:
          type: string
        networkType:
          type: string
          enum: 
            - stagenet
            - mainnet
            - testnet
          default: mainnet
        primaryAddress:
          type: string
        privateViewKey:
          type: string
        restoreHeight:
          type: integer
      required:
        - path
        - primaryAddress
        - privateViewKey
        - restoreHeight
    WalletSync:
      type: object
      properties:
        path:
          type: string
        networkType:
          type: string
          enum: 
            - stagenet
            - mainnet
            - testnet
          default: mainnet
        serverUri:
          type: string
      required:
        - path
        - serverUri
    MakeInvoice:
      type: object
      properties:
        path:
          type: string
        payment_id:
          type: string
        amount: 
          type: integer
        currency:
          type: string
          default: usd
    MakeInvoiceResponse:
      type: object
      properties:
        address:
          type: string
        address_qrcode:
          type: string
        amount:
          type: integer
    SuccessResponse:
      type: object
      properties:
        message:
          type: string
    WalletShutdown:
      type: array
      items:
        type: string
    WalletStatusResponse:
      type: array
      items:
        type: object
        properties:
          path:
            type: string
          status:
            type: string
            enum:
              - synching
              - not synching
        required:
          - status
          - path
      
tags:
  - name: startup tasks
    description: initialize & reopen & sync
  - name: accept payments & check api health
  - name: shutdown tasks 